[package]
name = "label-logger"
description = "A Cargo-like logging library"
repository = "https://github.com/MrNossiom/label_logger"
license = "MIT"
version = "1.0.0-alpha.9"
edition = "2021"

[dependencies]
console = "0.15.0"
dialoguer = { version = "0.10.0", optional = true }
lazy_static = "1.4.0"
term_size = "0.3.2"

[features]
default = []
dialoguer = ["dep:dialoguer", "dialoguer/fuzzy-select", "dialoguer/password"]
