[package]
name = "label-logger"
description = "A Cargo-like logging library"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
term_size = "0.3.2"
yansi = "0.5.0"
